name: 'dbt_scripts'
version: '1.0.0'

profile: 'dbt_scripts'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_scripts:
    fact:
      +materialized: incremental
    stg:
      +materialized: view
    dim:
      +materialized: table